changed indentation

diff --git a/deinstall b/deinstall
--- a/deinstall
+++ b/deinstall
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 if [ ! -f "./INSTALL_PREFIX" ]; then
-	echo "install prefix not defined! aborting!" 1>&2
-	exit
+    echo "install prefix not defined! aborting!" 1>&2
+    exit
 fi
 
 INSTALL_PREFIX="`cat ./INSTALL_PREFIX`"
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,17 +1,17 @@
 #!/bin/sh
 
 if [ ! -f "./INSTALL_PREFIX" ]; then
-	echo "install prefix not defined! aborting!" 1>&2
-	exit
+    echo "install prefix not defined! aborting!" 1>&2
+    exit
 fi
 
 INSTALL_PREFIX="`cat ./INSTALL_PREFIX`"
 
 if [ ! "`command -v cargo`" = "" ]; then
-	echo "-- cargo found"
+    echo "-- cargo found"
 else
-	echo "cargo required to compile ser! aborting!" 1>&2
-	exit
+    echo "cargo required to compile ser! aborting!" 1>&2
+    exit
 fi
 
 echo "-- compiling ser"
diff --git a/scripts/dm b/scripts/dm
--- a/scripts/dm
+++ b/scripts/dm
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 usage() {
-	echo "USAGE: dm [-h, --help] [-a,--allow-non-text] [-o, --output-dir <DIR>] [SOURCE]"
+    echo "USAGE: dm [-h, --help] [-a,--allow-non-text] [-o, --output-dir <DIR>] [SOURCE]"
 }
 
 OUTPUT_DIR=".out"
@@ -9,71 +9,71 @@ ONLY_TEXT=true
 FILE_TO_SOURCE=""
 
 while [ "$#" -gt 0 ]; do
-	case $1 in
-		-h | --help)
-			usage
-			exit
-			;;
-		-a | --allow-non-text)
-			ONLY_TEXT=false
-			;;
-		-o | --output-dir)
-			if [ ! "$2" = "" ]; then
-				OUTPUT_DIR="$2"
-				shift 2
-			else
-				echo "no output directory provided! aborting!" 1>&2
-				exit
-			fi
-			;;
-		*)
-			if [ "$FILE_TO_SOURCE" = "" ]; then
-				FILE_TO_SOURCE="$1"
-			else
-				echo "invalid argument '$1'! aborting!" 1>%&2
-				exit
-			fi
-			;;
-	esac
-	shift
+    case $1 in
+        -h | --help)
+            usage
+            exit
+            ;;
+        -a | --allow-non-text)
+            ONLY_TEXT=false
+            ;;
+        -o | --output-dir)
+            if [ ! "$2" = "" ]; then
+                OUTPUT_DIR="$2"
+                shift 2
+            else
+                echo "no output directory provided! aborting!" 1>&2
+                exit
+            fi
+            ;;
+        *)
+            if [ "$FILE_TO_SOURCE" = "" ]; then
+                FILE_TO_SOURCE="$1"
+            else
+                echo "invalid argument '$1'! aborting!" 1>%&2
+                exit
+            fi
+            ;;
+    esac
+    shift
 done
 
 echo "output directory: $OUTPUT_DIR"
 echo "disallow non-text files: $ONLY_TEXT"
 
 if [ ! "$FILE_TO_SOURCE" = "" ]; then
-	echo "sourcing file '$FILE_TO_SOURCE'"
-	. $FILE_TO_SOURCE
+    echo "sourcing file '$FILE_TO_SOURCE'"
+    . $FILE_TO_SOURCE
 fi
 
 read -p "is this directory [$(pwd)] correct? (y/N): " confirmation
 
 case $confirmation in
-	[yY][eE][sS]|[yY])
-		echo "continuing"
-		;;
-	*)
-		echo "aborting!"
-		exit
-		;;
+    [yY][eE][sS]|[yY])
+        echo "continuing"
+        ;;
+    *)
+        echo "aborting!"
+        exit
+        ;;
 esac
 
 SER="ser"
 
 echo "checking for 'ser'"
 if [ "$(command -v ser)" = "" ]; then
-	if [ -x "./ser" ]; then
-		SER="./ser"
-	else
-		echo "'ser' not found! aborting!" 1>&2
-		exit
-	fi
+    if [ -x "./ser" ]; then
+        SER="./ser"
+    else
+        echo "'ser' not found! aborting!" 1>&2
+        exit
+    fi
 fi
 echo "found 'ser'"
 
 if [ -d "$OUTPUT_DIR" ]; then
-	echo "deleting previous output"
-	rm -r $OUTPUT_DIR
+    echo "deleting previous output"
+    rm -r $OUTPUT_DIR
 fi
 
 echo "deleting broken symlinks"
@@ -83,18 +83,18 @@ mkdir $OUTPUT_DIR
 
 echo "duplicating directory tree"
 for dir in */; do
-	cp -a $dir $OUTPUT_DIR
+    cp -a $dir $OUTPUT_DIR
 done
 
 for entry in $(find $OUTPUT_DIR/); do
-	if [ -f $entry ]; then
-		if file --mime-type $entry | grep -q "^.*: text/.*" || [ $ONLY_TEXT = false ]; then
-			echo "generating '$entry'"
-			printf "%s" "$($SER "$entry")" > $entry
-		else
-			echo "skipping '$entry'"
-		fi
-	fi
+    if [ -f $entry ]; then
+        if file --mime-type $entry | grep -q "^.*: text/.*" || [ $ONLY_TEXT = false ]; then
+            echo "generating '$entry'"
+            printf "%s" "$($SER "$entry")" > $entry
+        else
+            echo "skipping '$entry'"
+        fi
+    fi
 done
 
 echo "symlinking generated files"
